#ifndef VISUALIZATION_GLOBAL_H
#define VISUALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef VISUALIZATION_LIB
# define VISUALIZATION_EXPORT Q_DECL_EXPORT
#else
# define VISUALIZATION_EXPORT Q_DECL_IMPORT
#endif

#endif // VISUALIZATION_GLOBAL_H
